In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv("path/to/filtered_dataset.csv", header=0)
df["consistency"] = df["consistency"].map({True: "Consistent", False : "Inconsistent"})
df["body"] = df["body"].map(lambda x : x.replace(" ", "").split("\" comment")[0]).tolist()

In [3]:
inconsistent_dfs = {category: df[df["injected_pattern"] == category] for category in df["injected_pattern"].unique() if pd.notna(category)}
consistent_df = df[df["consistency"] == "Consistent"].sample(frac=1, random_state=42).reset_index(drop=True)

In [4]:
train_df = pd.DataFrame(columns=["file_name", "consistency", "tokenized_length", "body", "injected_pattern"])
eval_df = pd.DataFrame(columns=["file_name", "consistency", "tokenized_length", "body", "injected_pattern"])
test_df = pd.DataFrame(columns=["file_name", "consistency", "tokenized_length", "body", "injected_pattern"])

In [5]:
train_df = pd.concat([train_df, consistent_df[:int(len(consistent_df)*0.7)]])
eval_df = pd.concat([eval_df, consistent_df[int(len(consistent_df)*0.7): int(len(consistent_df)*0.85)]])
test_df = pd.concat([test_df, consistent_df[int(len(consistent_df)*0.85):]])

In [6]:
inconsistent_dfs.keys()

dict_keys(['OIL', 'OILWI', 'UEWPI', 'SOSINETO', 'UEWIP', 'OOD', 'OOR', 'UEWI2', 'UEWI1', 'EID', 'CSC', 'UE', 'AIO'])

In [7]:
for _, dataframe in inconsistent_dfs.items():
    dataframe = dataframe.sample(frac=1, random_state=42).reset_index(drop=True)
    train_df = pd.concat([train_df, dataframe[:int(len(dataframe)*0.7)]])
    eval_df = pd.concat([eval_df, dataframe[int(len(dataframe)*0.7): int(len(dataframe)*0.85)]])
    test_df = pd.concat([test_df, dataframe[int(len(dataframe)*0.85):]])

In [8]:
train_df.to_csv("train_data.csv",index=False)
eval_df.to_csv("eval_data.csv",index=False)
test_df.to_csv("test_data.csv",index=False)

In [14]:
eval_df[eval_df["consistency"] == "Consistent"]

,file_name,consistency,tokenized_length,body,injected_pattern
2918,WB-PHENOTYPE_Module_11.jsonl,Consistent,3064,"[['WBPhenotype_0000003','is','Class'],['WBPhen...",NaN
2919,GDCO_Module_6.jsonl,Consistent,721,"[['BFO_0000050','is','ObjectProperty'],['BFO_0...",NaN
2920,RS_Module_14.jsonl,Consistent,2898,"[['RS_0000064','is','Class'],['RS_0000064','Su...",NaN
2921,CTENO_Module_3.jsonl,Consistent,3715,"[['BFO_0000050','is','ObjectProperty'],['RO_00...",NaN
2922,DUO_Module_6.jsonl,Consistent,467,"[['BFO_0000050','is','ObjectProperty'],['BFO_0...",NaN
...,...,...,...,...,...
3538,LICO_Module_0.jsonl,Consistent,3412,"[['boolean','is','Datatype'],['date','is','Dat...",NaN
3539,CMECS_Module_0.jsonl,Consistent,3622,"[['CMECS_00000014','is','Class'],['CMECS_00000...",NaN
3540,PINO_Module_1.jsonl,Consistent,1319,"[['Solid_foods_–_Timing','is','Class'],['Solid...",NaN
3541,BIOMO_Module_13.jsonl,Consistent,2797,"[['double','is','Datatype'],['SIO_000008','is'...",NaN
3542,CRISP_Module_7.jsonl,Consistent,596,"[['0080-9038','is','Class'],['0080-9038','SubC...",NaN

In [15]:
eval_df[eval_df["consistency"] == "Inconsistent"]

,file_name,consistency,tokenized_length,body,injected_pattern
2,UEWPI_1_DREAMDNPTO_Module_4.jsonl,Inconsistent,3505,"[['causes','is','ObjectProperty'],['causes','D...",UEWPI
4,SOSINETO_1_NONRCTO_Module_0.jsonl,Inconsistent,1964,"[['www.-ontologies.com/RCTOntology.#','is','Ob...",SOSINETO
14,UEWIP_1_DRPSNPTO_Module_5.jsonl,Inconsistent,2968,"[['affects','is','ObjectProperty'],['affects',...",UEWIP
15,UEWIP_1_MACROALGAETRAITS_Module_0.jsonl,Inconsistent,483,"[['causes','is','ObjectProperty'],['causes','D...",UEWIP
16,UEWIP_1_NIGO_Module_2.jsonl,Inconsistent,624,"[['isBackgroundOf','is','ObjectProperty'],['is...",UEWIP
...,...,...,...,...,...
452,AIO_2_ONTOLURGENCES_Module_31.jsonl,Inconsistent,3200,"[['www.w3.org/2000/01/-schema#','is','Annotati...",AIO
453,AIO_2_ONTOLURGENCES_Module_29.jsonl,Inconsistent,2744,"[['motifACommeOrigineDiagnostic','is','ObjectP...",AIO
454,AIO_2_ONTOPSYCHIA_Module_19.jsonl,Inconsistent,2582,"[['a_partie','is','ObjectProperty'],['a_partie...",AIO
455,AIO_2_XAO_Module_6.jsonl,Inconsistent,3547,"[['www.w3.org/2000/01/-schema#','is','Annotati...",AIO
456,AIO_2_PMR_Module_10.jsonl,Inconsistent,1230,"[['www.w3.org/2000/01/-schema#','is','Annotati...",AIO